export enum InfrastructureProviderEnum {
  REDIS_SERVICE = 'INFRASTRUCTURE_REDIS_SERVICE',
  LOGGER_SERVICE = 'INFRASTRUCTURE_LOGGER_SERVICE',
  HTTP_SERVICE = 'INFRASTRUCTURE_HTTP_SERVICE',
  EXAMPLE_HTTP_SERVICE = 'INFRASTRUCTURE_EXAMPLE_HTTP_SERVICE',

  // Postgres
  POSTGRES_DATASOURCE = 'INFRASTRUCTURE_POSTGRES_DATASOURCE',
  POSTGRES_PROFILE_REPOSITORY = 'INFRASTRUCTURE_POSTGRES_PROFILE_REPOSITORY'
}
