export enum InfrastructureProviderEnum {
  REDIS_SERVICE = 'INFRASTRUCTURE_REDIS_SERVICE',
  LOGGER_SERVICE = 'INFRASTRUCTURE_LOGGER_SERVICE',
  XLS_READER_SERVICE = 'INFRASTRUCTURE_XLS_READER_SERVICE',

  // Postgres
  POSTGRES_DATASOURCE = 'INFRASTRUCTURE_POSTGRES_DATASOURCE',
  PROFILE_REPOSITORY = 'INFRASTRUCTURE_PROFILE_REPOSITORY'
}
