export enum PresentationProviderEnum {
  HEALTH_CHECK_CONTROLLER = 'PRESENTATION_HEALTH_CHECK_CONTROLLER',
  CREATE_PROFILE_CONTROLLER = 'PRESENTATION_CREATE_PROFILE_CONTROLLER',
  GET_PROFILE_BY_ID_CONTROLLER = 'PRESENTATION_GET_PROFILE_BY_ID_CONTROLLER',
  DELETE_PROFILE_BY_ID_CONTROLLER = 'PRESENTATION_DELETE_PROFILE_BY_ID_CONTROLLER',
  UPDATE_PROFILE_CONTROLLER = 'PRESENTATION_UPDATE_PROFILE_CONTROLLER',
  CREATE_PROFILE_FROM_XLS_CONTROLLER = 'PRESENTATION_CREATE_PROFILE_FROM_XLS_CONTROLLER',
}
