export enum PresentationProviderEnum {
  HEALTH_CHECK_CONTROLLER = 'PRESENTATION_HEALTH_CHECK_CONTROLLER',
  CREATE_PROFILE_CONTROLLER = 'PRESENTATION_CREATE_PROFILE_CONTROLLER',
  GET_PROFILE_BY_ID_CONTROLLER = 'PRESENTATION_GET_PROFILE_BY_ID_CONTROLLER',
}
