version: "3"
services:
  nginx_proxy:
    image: jwilder/nginx-proxy:latest
    container_name: stateful-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - statefuldev_network

  postgres:
    image: postgres:12-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
    networks:
      - statefuldev_network
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  redis:
    image: redis
    container_name: stateful-redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    hostname: redis
    command: redis-server --requirepass root
    restart: always
    volumes:
      - redis-data:/home/data:delegated
    ports:
      - "6379:6379"
    networks:
      - statefuldev_network

volumes:
  redis-data:
  postgres-data:

networks:
  statefuldev_network:
    external: true