export enum DomainProviderEnum {
  HEALTH_CHECK_USE_CASE = 'DOMAIN_HEALTH_CHECK_USE_CASE',
  CREATE_PROFILE_USE_CASE = 'DOMAIN_CREATE_PROFILE_USE_CASE',
  GET_PROFILE_BY_EMAIL_USE_CASE = 'DOMAIN_GET_PROFILE_BY_EMAIL_USE_CASE',
}
